resources:
  - https://github.com/kubevirt/kubevirt/releases/download/v0.60.0-alpha.0/kubevirt-operator.yaml
  - https://github.com/kubevirt/kubevirt/releases/download/v0.60.0-alpha.0/kubevirt-cr.yaml
