kind: ConfigMap
apiVersion: v1
metadata:
  name: 'slurmctl-prologs'
  namespace: 'slurm-cluster'
data:
  beeond: |
    #!/bin/bash

    set -ex

    export PATH="$PATH:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin"

    nodefile="/tmp/slurm_nodelist.${SLURM_JOB_ID}"
    datadir="/mnt/scratch/beeond"
    clientdir="/opt/scratch"
    logfile="/var/log/beeond/beeond.log"

    if [[ "${SLURM_JOB_PARTITION}" == *"beeond"* ]]; then
      scontrol show hostnames "${SLURM_JOB_NODELIST}" > "${nodefile}"
      timeout 60 sudo beeond start -n "${nodefile}" -d "${datadir}" -c "${clientdir}" -P -F >> $logfile 2>&1
    fi
