apiVersion: v2
name: kube-prometheus-stack-subchart
description: Kube Prometheus Stack subchart
type: application
version: 52.1.0
appVersion: '36.2.1'

dependencies:
  - name: kube-prometheus-stack
    version: 65.8.1
    repository: https://prometheus-community.github.io/helm-charts
