apiVersion: v2
name: kube-prometheus-stack-subchart
description: Kube Prometheus Stack subchart
type: application
version: 41.7.4
appVersion: '36.2.1'

dependencies:
  - name: kube-prometheus-stack
    version: 41.9.0
    repository: https://prometheus-community.github.io/helm-charts
